### PR TITLE
Upgrade datafusion version to 27.0.0

### PR DESCRIPTION
**Pull request by yukkit**
# Required checklist
- [ ] Sample config files updated (`config`,`meta/config` and `default config`) 
- [ ] If there are user-facing changes, the documentation needs to be updated prior to approving the PR( [Link]() )
- [ ] If there are any breaking changes to public APIs, please add the `api change` label.
- [ ] Signed [CLA](https://cla-assistant.io/cnosdb/cnosdb) (if not already signed)

# Which issue does this PR close?

[//]: # (We generally require a GitHub issue to be filed for all bug fixes and enhancements and this helps us generate change logs for our releases. You can link an issue to this PR using the GitHub syntax. For -- example `Closes #123` indicates that this PR will close issue #123.)

Related #1310 .

# Rationale for this change

[//]: # (Why are you proposing this change? If this is already explained clearly in the issue then this section is not needed.
 Explaining clearly why changes are proposed helps reviewers understand your changes and offer better suggestions for fixes.)

# Are there any user-facing changes?

[//]: # (There is no need to duplicate the description in the issue here, but it is sometimes worth providing a summary of the individual changes in this PR.)

### CODE REVIEW

**Comment by yukkit** [comment]
begin benchmark

**Comment by yukkit** [comment]
begin benchmark

**Comment by roseboy-liu** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_c4814f8.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_c4814f8.html

**Comment by roseboy-liu** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_c4814f8.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_c4814f8.html

**Review by roseboy-liu — APPROVED** [review]

**Pull request merged**
