### PR TITLE
feat(example): add first tutorial of tensorflow

### PR DESCRIPTION
**Pull request by DjangoPeng**
**PLEASE DON'T MERGE**

This is the first tutorial that introduces how to use `TensorFlow` and `CnosDB`  to solve real-world problems.

This tutorial uses the interactive programming environment Jupyter Notebook, which is preferred by Python data engineers. It not only illustrates the scientific value of predicting sunspot changes, but also demonstrates how to use CnosDB to read and write the Sunspot dataset. Finally, TensorFlow is used to reproduce the `1DConv+LSTM` neural network and experimental results from the research paper.

image

Sunspots are solar activity phenomena that occur on the solar photosphere and usually appear in groups. Predicting changes in sunspots is one of the most active areas of research in space weather. 

Given the profound impact that sunspot activity levels have on the Earth, detecting sunspot activity is particularly important. Physical models such as dynamic models [3] and statistical models such as autoregressive moving average [4] have been widely used to detect sunspot activity. In order to more efficiently capture the nonlinear relationships that exist in sunspot time series data, machine learning methods have been introduced. 

Therefore, this article will introduce how to use the time series database CnosDB to store sunspot data and further use TensorFlow to implement a 1DConv+LSTM network to predict changes in sunspot numbers.

### CODE REVIEW

**Comment by DjangoPeng** [comment]
It seems that there are errors when writing the sunspot dataset back to CnosDB in Cell 10 and Cell 11, using the write_lines and execute methods, respectively. Could you provide more details on the errors that you encountered? Additionally, it might be helpful to check if the necessary libraries and packages are installed and configured properly.


image

**Comment by DjangoPeng** [comment]
@Subsegment @cnoshb PTAL

**Comment by Subsegment** [comment]
Tag is required when writing using the line protocol.
If you want time to be an index, use this`conn.create_database_with_ttl("tf_demo", "100000d")`to create database.
In addition, use this `query = f"INSERT INTO sunspot (time, date, mssn) VALUES ({index}, {row['date']}, {row['mssn']})"` to build query

**Comment by DjangoPeng** [comment]
> Tag is required when writing using the line protocol.

According to the InfluxDB development documentation, I learned that line protocol is a line-based text protocol that requires at least one tag to uniquely identify a data point. If a data point is missing a tag, it may lead to data ambiguity and inaccuracy. 

**So in our scenario, I cannot use the data write interface of the Python Client, and instead must use SQL queries.**

The SQL Query for writing data is a typo. 

I have corrected it, please see the screenshot below.

image

@Subsegment

**Comment by DjangoPeng** [comment]
The overall structure of the Example is sort of complete, can you see if you can complete the part of CnosDB I/O? 

@Subsegment

**Comment by Subsegment** [comment]
> The overall structure of the Example is sort of complete, can you see if you can complete the part of CnosDB I/O?
> 
> @Subsegment

`conn.create_database_with_ttl("tf_demo", "100000d")` 这个也改了吗

**Comment by Subsegment** [comment]
> The overall structure of the Example is sort of complete, can you see if you can complete the part of CnosDB I/O?
> 
> @Subsegment

`conn.create_database_with_ttl("tf_demo", "100000d")` create database should like this

**Comment by Subsegment** [comment]
https://peps.python.org/pep-0249/#cursor-methods

If using cursor, `fetch_all` can be used to get all the data, or `conn.execute("select * from sunspot;") `can be used directly. 

:)

**Comment by DjangoPeng** [comment]
LGTM

@Subsegment PTAL

**Review by Subsegment — APPROVED** [review]

**Pull request merged**
