### PR TITLE
improve: decrease clone

### PR DESCRIPTION
**Pull request by ZuoTiJia**
# Required checklist
- [x] Sample config files updated (`config`,`meta/config` and `default config`) 
- [x] If there are user-facing changes, the documentation needs to be updated prior to approving the PR( [Link]() )
- [x] If there are any breaking changes to public APIs, please add the `api change` label.
- [x] Signed [CLA](https://cla-assistant.io/cnosdb/cnosdb) (if not already signed)

there are some clone

https://github.com/cnosdb/cnosdb/blob/5378a3d6e12ccde5a8c2236eca1349caf6f7eb86/tskv/src/reader/iterator.rs#L744-L747
https://github.com/cnosdb/cnosdb/blob/5378a3d6e12ccde5a8c2236eca1349caf6f7eb86/tskv/src/reader/iterator.rs#L88-L95

### CODE REVIEW

**Comment by ZuoTiJia** [comment]
begin benchmark

**Comment by roseboy-liu** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_ba395be.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_ba395be.html

**Comment by ZuoTiJia** [comment]
begin benchmark

**Comment by roseboy-liu** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_0b8d521.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_0b8d521.html

**Review by roseboy-liu — APPROVED** [review]

**Pull request merged**
