### PR TITLE
Refactor write

### PR DESCRIPTION
**Pull request by ZuoTiJia**
# Required checklist
- [x] Sample config files updated (`config`,`meta/config` and `default config`) 
- [x] If there are user-facing changes, the documentation needs to be updated prior to approving the PR( [Link]() )
- [x] If there are any breaking changes to public APIs, please add the `api change` label.
- [x] Signed [CLA](https://cla-assistant.io/cnosdb/cnosdb) (if not already signed)

### CODE REVIEW

**Comment by ZuoTiJia** [comment]
begin benchmark

**Comment by ZuoTiJia** [comment]
begin benchmark

**Comment by roseboy-liu** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_8fa7c9e.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_8fa7c9e.html

**Comment by roseboy-liu** [comment]
https://cnosdb-admin.teleport.cnosdb.com/benchmark-hits/hits_8fa7c9e.html
https://cnosdb-admin.teleport.cnosdb.com/benchmark-tsbs/tsbs_8fa7c9e.html

**Review by roseboy-liu — APPROVED** [review]

**Pull request merged**
